#version: "3"
#services:
#  selenium-hub:
#    image: selenium/hub:3.141.59-20210929
#    container_name: selenium-hub
#    ports:
#      - "0.0.0.0:4444:4444"
#
#  chrome:
#    image: selenium/node-chrome:3.141.59-20210929
##    volumes:
##      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#
##  testimage:
##    image: testmaven
##    depends_on:
##      - chrome
##    environment:
##      - HUB_HOST=selenium-hub
##    volumes:
###      - ./reports:/app/target
##      - "C:/Users/ATereshin/.m2:/root/.m2"
###      - "C:/Users/ATereshin/Desktop/start_test.sh:/app/start_test.sh"

version: '3.5'

networks:
  selenoid:

services:

  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid:latest-release"
    ports:
      - "0.0.0.0:4444:4444"
    volumes:
      - ./config/:/etc/selenoid/:ro
      - ./video:/opt/selenoid/video
      - ./logs:/opt/selenoid/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "ui-test_selenoid", "-limit", "10", "-retry-count", "2"]
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=C:/docker/video/"
    networks:
      selenoid:

  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:latest-release"
    links:
      - selenoid
    ports:
      - "0.0.0.0:8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      selenoid: